%Plotter to see stored data

close all;
%[file, path] = uigetfile('*.*', 'Seleccionar el historial', 'simulations\');
file = 'PaperFigure5_new.csv';
path = 'D:\GITRepos\MyFiles\Matlab\WaveEq\AxisSymmetricv_1.8\simulations\';
if isequal(file, 0)
    return;
else
    conffigs = detectImportOptions(fullfile(path, file));
    conffigs.VariableTypes{1} = 'string';
    conffigs.PreserveVariableNames = true;
    %conffigs.SelectedVariableNames = {'ID', 'vi', 'surfaceTension', 'radius'};
    values = readtable(fullfile(path, file), conffigs);
    values = values(isfinite(values.coefOfRestitution), :);
    values = sortrows(values, {'radius', 'vi'}, {'ascend', 'descend'});
end

PLOTTING_VARIABLE = 'cTime';


%% Settings of radii to be plotted
CATEGORIES = {   0.350;    0.500;    0.795;    0.850; ...
                 0.900;    0.950;    0.995;    1.150; ...
                 1.250;    1.350;    1.750;    2.000; ...
                 2.380;    2.780;    3.000;    3.175};
MARKERS    = {     'o';      '>';      's';      '>'; ...
                   'x';      '*';      '+';      '<'; ...
                   'v';      'p';      '^';      'p'; ...
                   'h';      'v';      'd';      '+'};
LINEWIDTHS = {     2.9;        2;        2;        2; ...
                   3.5;        3;        4;        2; ...
                     2;        2;        4;        2; ...
                     2;        2;        2;        2};
LINESTYLES = {     '-';      '-';      '-';      '-'; ...
                  '--';     '--';     '--';      '-'; ...
                   '-';      '-';      '-';      '-'; ...
                   '-';      '-';      '-';      '-'};
COLORS     ={'#e69600';'#d55c00';'#000000';'#AAAAAA';...
             '#56b3e9';'#f0e442';'#009e74';'#AAAAAA';...
             '#AAAAAA';'#AAAAAA';'#0072b2';'#AAAAAA';...
             '#AAAAAA';'#cc79a7';'#cc79a7';'#AAAAAA'};
configs = struct('radius', CATEGORIES, 'markers', MARKERS, 'LineWidths', LINEWIDTHS, ...
    'LineStyles', LINESTYLES, 'Color', COLORS);
LL = length(configs);


%% Coefficient of restitution
%PANEL (a)
figureCoefOfRestitution = figure(1);
set(gcf,'position',[100, 100, 560, 420], 'Units', 'pixels');

set(gca, ...
  'Box'         , 'on'      , ...
  'FontSize'    , 16        , ...
  'TickDir'     , 'in'      , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XTick'       , 0:0.25:2  , ... %
  'YTick'       , -1:0.25:1 , ...
  'LineWidth'   , 1         );
hold on; grid on;
xlim([-.05 1.25]);
ylim([-.5, 1.05]);
xlabel('$ V_{0} \ (ms^{-1}) $', 'Interpreter', 'latex', 'FontSize', 24);
ylabel('$\alpha^{2} \ \ \ \ $', 'Interpreter', 'latex', 'Rotation', 0, ...
      'FontSize', 24);

Legends = cell(length(CATEGORIES), 1);

for jj= 1:length(CATEGORIES)
    subvalues = values(abs(values.radius - CATEGORIES{jj}) < 0.03, :);
    if isempty(subvalues) == true
        continue;
    end
    plot(abs(subvalues.vi), subvalues.coefOfRestitution, ...
        'LineStyle', configs(jj).LineStyles, ...
        'LineWidth', configs(jj).LineWidths, ...
        'Color'    , configs(jj).Color);
    
    Legends{jj} = sprintf('$ R = %.3f \\ (mm)$', configs(jj).radius);
end
Legends = Legends(~cellfun(@isempty, Legends));
legend(Legends, 'Location', 'SouthEast', 'FontSize', 14, ...
    'Interpreter', 'latex', 'AutoUpdate', 'off');

% Big velocities with markers
for jj= 1:length(CATEGORIES)
    subvalues = values(abs(values.radius - CATEGORIES{jj}) < 0.03, :);
    subvalues = subvalues(isnan(subvalues.maxDeflection), :);
    subvalues = subvalues(abs(subvalues.vi) > 0.1, :);
    if isempty(subvalues) == true
        subvalues = values(abs(values.radius - CATEGORIES{jj}) < 0.03, :);
        subvalues = subvalues(abs(subvalues.vi) > 0.1, :);
        scatter(abs(subvalues.vi), subvalues.coefOfRestitution, ...
            'SizeData'       , 100              , ...
            'LineWidth'      , 1.5              , ...
            'MarkerFaceColor', [.7 .7 .7]       , ...
            'MarkerEdgeColor', 'black'          , ...
            'Marker'         , configs(jj).markers);
    else
        scatter(abs(subvalues.vi), subvalues.coefOfRestitution, ...
            'SizeData'       , 100              , ...
            'LineWidth'      , 1.5              , ...
            'MarkerFaceColor', [.7 .7 .7]       , ...
            'MarkerEdgeColor', configs(jj).Color, ...
            'Marker'         , configs(jj).markers);
    end
end
tt = text(.02, -0.35, '$a)$', 'Interpreter', 'latex', 'FontSize', 20);
print(figureCoefOfRestitution, '-depsc', '-r300', 'Graficos/coefOfRestitution_panel_a_v2.eps');


% Small velocities
figureSmallCoef = figure(2);

set(gcf,'position',[700, 100, 800, 420], 'Units', 'pixels');

set(gca, ...
  'Box'         , 'on'      , ...
  'FontSize'    , 16        , ...
  'TickDir'     , 'in'      , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ... 
  'YTick'       , -1:0.25:1 , ...
  'LineWidth'   , 1         );
hold on; grid on;
xlim([0 0.05]);
ylim([-.5, 1.05]);
xlabel('$ V_{0} \ (ms^{-1}) $', 'Interpreter', 'latex', 'FontSize', 24);
%ylabel('$\alpha^{2} \ \ \ \ $', 'Interpreter', 'latex', 'Rotation', 0, ...
%      'FontSize', 24);

for jj= 1:length(CATEGORIES)
    subvalues = values(abs(values.radius - CATEGORIES{jj}) < 0.03, :);
    if isempty(subvalues) == true
        continue;
    end
    plot(abs(subvalues.vi), subvalues.coefOfRestitution, ...
        'LineStyle', configs(jj).LineStyles, ...
        'LineWidth', configs(jj).LineWidths, ...
        'Color'    , configs(jj).Color);
end
tt = text(.002, -0.35, '$b)$', 'Interpreter', 'latex', 'FontSize', 20);
print(figureSmallCoef, '-depsc', '-r300', 'Graficos/coefOfRestitution_panel_b_v2.eps');
