
cats = {0.90, 0.95, 0.995};
%Physical constants
Tm = 27; %11.6164; %Tension of the material (in mg / ms^2)
for iii = 1:length(cats)
    rS = cats{iii}; %Radius of the sphere (in mm)
    for vi = 0.35:0.3:1.2
        name = sprintf('appendCORTm%g.csv', Tm);
        mainFunction1_8(rS, Tm, ...
            'v_k'     , -abs(vi), ...
            'N'       , 100, ...
            'plotter' , false, ...
            'FileName', name, ...
            'exportData', true ...
            );
    end
end