
cats = {0.85; 0.90; 0.95};
%Physical constants
Tm = 28; %11.6164; %Tension of the material (in mg / ms^2)
for iii = 1:length(cats)
    rS = cats{iii}; %Radius of the sphere (in mm)
    for vi = 0.2:0.3:1.2
        name = sprintf('historialCoefOfRestitutionTm%g.csv', Tm);
        mainFunction1_8(rS, Tm, ...
            'v_k'     , -abs(vi), ...
            'RecordedTime', 1e-3, ...
            'plotter' , false, ...
            'FileName', name, ...
            'exportData', true ...
            );
    end
end