 %Physical constants
clear variables;
rS = 0.795; %Radius of the sphere (in mm)
R_f = 7.95/rS; %Number of raddi in half a length of the membrane (dimensionless)
Tm = 73;%50.6164; %Tension of the material (in mg / ms^2)
g = 9.80665e-3; %Gravity of earth (in mm/ms^2)
mu = 1.68e-2; %Density of membrane per unit of area (mg/mm^2) (Sara Wrap membrane)
%mS = 73.8 * 4 * pi * (rS.^3) / 3;%7.8 * 4 * pi * (rS.^3) / 3; %Mass of the ball (in mg) (7.8 is the ball's 
%density in mg/mm^3)



mainFunction1_8(rS, Tm, ...
    'v_k', -0.50323, ...
    'plotter', true, ...
    'RecordedTime', 0.005, ...
    'FileName', 'historialPlot.csv', ...
    'method', 'Euler', ...
    'exportData', false, ...
    'saveAfterContactEnded', false, ...
    'SimulTime', 30 ...
    );

% mainFunction1_8(rS, Tm, ...
%     'v_k', -0.7806451613, ...
%     'plotter', true, ...
%     'RecordedTime', 0.001, ...
%     'FileName', 'historialPlot.csv', ...
%     'method', 'Euler', ...
%     'exportData', true, ...
%     'saveAfterContactEnded', false);