 %Physical constants
clear variables;
rS = 0.795; %Radius of the sphere (in mm)
R_f = 52.4/rS; %Number of raddi in half a length of the membrane (dimensionless)
Tm = 27;%50.6164; %Tension of the material (in mg / ms^2)
g = 9.80665e-3; %Gravity of earth (in mm/ms^2)
mu = 1.68e-2; %Density of membrane per unit of area (mg/mm^2) (Sara Wrap membrane)
%mS = 73.8 * 4 * pi * (rS.^3) / 3;%7.8 * 4 * pi * (rS.^3) / 3; %Mass of the ball (in mg) (7.8 is the ball's 
%density in mg/mm^3)


solveMotion1_8(1, 2, 10, ...
    'z_k', 1.3, ...
    'v_k', -0.30323, ...
    'N',   50, ...
    'RecordedTime', 1e-2, ...
    'plotter', true, ...
    'FileName', 'newhistorialPlot.csv', ...
    'method', 'Euler', ...
    'exportData', true, ...
    'saveAfterContactEnded', true, ...
    'SimulTime', 15 ...
    );

% mainFunction1_8(0.35, 27, ...
%     'v_k', -0.0032788779, ...
%     'N',   150, ...
%     'plotter', true, ...
%     'FileName', 'historialPlot.csv', ...
%     'method', 'Euler', ...
%     'exportData', false, ...
%     'saveAfterContactEnded', false, ...
%     'SimulTime', 20 ...
%     );

% mainFunction1_8(0.95, 27, ...
%     'v_k', -0.0078125, ...
%     'RecordedTime', 5e-4, ...
%     'N',   200, ...
%     'plotter', true, ...
%     'FileName', 'historialPlot.csv', ...
%     'method', 'Euler', ...
%     'exportData', true, ...
%     'saveAfterContactEnded', false, ...
%     'SimulTime', 20 ...
%     );

% mainFunction1_8(0.995, 27, ...
%     'v_k', -0.004915625, ...
%     'N',   150, ...
%     'plotter', true, ...
%     'FileName', 'historialPlot.csv', ...
%     'method', 'Euler', ...
%     'exportData', false, ...
%     'saveAfterContactEnded', false, ...
%     'SimulTime', 20 ...
%     );

% mainFunction1_8(rS, Tm, ...
%     'v_k', -0.7806451613, ...
%     'plotter', true, ...
%     'RecordedTime', 0.001, ...
%     'FileName', 'historialPlot.csv', ...
%     'method', 'Euler', ...
%     'exportData', true, ...
%     'saveAfterContactEnded', false);