
cats = {1.75, 3}; 
%Physical constants
Tm = 27; %11.6164; %Tension of the material (in mg / ms^2)
name = sprintf('historialRestitution%g.csv', Tm);
r = 0;
for iii = 1:length(cats)
    rS = cats{iii}; %Radius of the sphere (in mm)
    mainFunction1_8(rS, Tm, ...
            'v_k'     , -0.05, ...
            'N'       , 250, ...
            'plotter' , false, ...
            'FileName', name, ...
            'exportData', true ...
            );
        
    mainFunction1_8(rS, Tm, ...
        'v_k'     , -0.04, ...
        'N'       , 250, ...
        'plotter' , false, ...
        'FileName', name, ...
        'exportData', true ...
        );
    for vi = 0.030:(-0.001):0.001
        rnew = mainFunction1_8(rS, Tm, ...
            'v_k'     , -abs(vi), ...
            'N'       , 250, ...
            'plotter' , false, ...
            'FileName', name, ...
            'exportData', true ...
            );
        if rnew > 1e+6 && r > 1e+6
            break;
        end
        r = rnew;
    end
end