
%Physical constants
Tm = 27; %11.6164; %Tension of the material (in mg / ms^2)
name = sprintf('historialRestitution%g.csv', Tm);
r = 0;

mainFunction1_8(0.795, Tm, ...
        'v_k'     , -0.003, ...
        'N'       , 400, ...
        'plotter' , false, ...
        'FileName', name, ...
        'exportData', true ...
        );
