
cats = {0.995}; %0.90; 0.95; 0.995};
%Physical constants
Tm = 27; %11.6164; %Tension of the material (in mg / ms^2)
name = sprintf('historialCoefOfRestitution995Tm%g.csv', Tm);
for iii = 1:length(cats)
    rS = cats{iii}; %Radius of the sphere (in mm)
    for vi = 0.0058125:0.001:0.0158125
        mainFunction1_8(rS, Tm, ...
            'v_k'     , -abs(vi), ...
            'N'       , 250, ...
            'plotter' , false, ...
            'FileName', name, ...
            'exportData', true ...
            );
    end
end