
%Physical constants

R_f = 105/2; % Membrane RADIUS (in mm)
Tm = 49.4;  %Linear tension of the material (in N / m = kg*m/(s2*m) = mg / ms^2)
rS = 4.76/2; %(both in mm)
mass = @(rS, rho) rho * (4*pi/3) * rS^3; % in mg
rho = 3.25; % also in mg/mm3
v0 = [0.6108; 0.6662; 0.7376; 0.8143; 0.8583; 0.8969; 0.9731]; % in  mm/ms = m/s
mu = 1.46e-2; %Density of membrane per unit of area (mg/mm^2) (Sara Wrap membrane)

for idx = 1:length(v0)
    v_k = v0(idx);
    solveMotion1_9(rS, Tm, R_f/rS, mu, mass(rS, rho), ...
            'v_k'     , -abs(v_k), ...
            'N'       , 150, ...
            'plotter' , false, ...
            'FileName', 'simulationDan_air_Saran.csv', ...
            'exportData', true ...
            );
end

% for vi = .5:.1:1.1
%     solveMotion1_9(rS, Tm, R_f/rS, mu, mass(rS, rho), ...
%             'v_k'     , -abs(vi), ...
%             'N'       , 150, ...
%             'plotter' , false, ...
%             'FileName', 'simulationDan_air(2).csv', ...
%             'exportData', true ...
%             );
% end