% This script will summarize relevant information about pressure at contact
% points in the kinematic match.

close all; clearvars;
snapshots = 10;

%% Reading the file to be analyzed
[file, path] = uigetfile('*.mat', 'Select a File', ...
    'simulations\');
load(fullfile(path, file), 'recordedPk', 'rt', 'N', 'rS');
[mii, Ntot] = size(recordedPk);


xAxis = linspace(0, 1, Ntot);
%% Plotting snapshots

perfil = figure('Units', 'pixels', 'position', [0 40 560 420]);
title('Perfil de presión en diversos tiempos', ...
        'FontSize', 14, 'FontName', 'Cambria');
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:25:100  , ...
  'XTick'       , 0:0.2:1   , ...
  'LineWidth'   , 1         , ...
  'TickLabelInterpreter', 'latex');
xlim([0, 1]);
xlabel('r/R_{s} (Adimensional', 'FontSize', 14, ...
    'FontWeight', 'bold', 'FontName', 'Cambria');
ylabel('Presión (Pa/m)', 'FontWeight', 'bold', ...
    'FontSize', 14, 'FontName', 'Cambria');  
grid on; hold on;

Legends = cell(snapshots, 1);
idxs = round(mii * linspace(1/mii, 1, snapshots));

for ii = 1:length(idxs)
    Pk = recordedPk(idxs(ii), :); 
    P = plot(xAxis, Pk, ...
        'LineWidth', 2, ...
        'Color', [idxs(ii) / mii, 0/256, (1- idxs(ii) / mii)]);
    Legends{ii} = sprintf('t = %5.2g ms', rt * idxs(ii));
end
legend(Legends, 'Location', 'NorthEast', 'FontSize', 12);

%% Plotting contact area

area = figure('Units', 'pixels', 'position', [980 40 560 420]);
title('Área presionada en función del tiempo', ...
        'FontSize', 14, 'FontName', 'Cambria');
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:0.1:1  , ...
  'XTick'       , 0:0.5:(mii*rt)   , ...
  'LineWidth'   , 1         , ...
  'TickLabelInterpreter', 'latex');
xlim([0, mii * rt]);
xlabel('Tiempo desde contacto (ms)', 'FontWeight', 'bold', ...
    'FontSize', 14, 'FontName', 'Cambria');
ylabel('r/R_{s} (Adimensional', 'FontSize', 14, ...
    'FontWeight', 'bold', 'FontName', 'Cambria');

figure(area); grid on; hold on;
carea = zeros(mii, 1);
for ii = 1:mii
    carea(ii) = length(recordedPk(ii, abs(recordedPk(ii, :)) > 0.0001)) / Ntot;
end

plot((1:mii) * rt, carea, ...
    'LineWidth'   , 2, ...
    'Color'       , 'r'); 

%% Plotting for video 

vid = figure('Units', 'pixels', 'position', [460 360 560 420]);
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:25:100  , ...
  'XTick'       , 0:0.2:1   , ...
  'LineWidth'   , 1         , ...
  'TickLabelInterpreter', 'latex');

xlim([0 1]);
xlabel('r/R_{s} (Adimensional', 'FontSize', 14, ...
    'FontWeight', 'bold', 'FontName', 'Cambria');
ylabel('Presión (Pa/m)', 'FontWeight', 'bold', ...
    'FontSize', 14, 'FontName', 'Cambria'); 

v = VideoWriter(fullfile(path, strrep(strrep(file, '.mat', '.avi'), 'simul', 'pressure')));
open(v);

figure(vid); grid on; hold on;
for ii = 1:mii
    cla;
    title(sprintf('t = %5.2f ms', rt*ii), 'interpreter', 'latex', ...
        'FontSize',16, 'FontName', 'Cambria Math');
    Pk = recordedPk(ii, :); 
    P = plot(xAxis, Pk);
    set(P, 'LineWidth'       , 3 ...
         , 'Color', 'r' );  
    pause(0.1); drawnow;
    writeVideo(v, getframe(gcf));
end
close(v);


