disp("value of pi:")
disp(%pi)
disp("value of eps:")
disp(%eps)
disp("Value of infinity:")
disp(%inf)
disp("Value of e:")
disp(%e)
disp("Value of imaginary number i:")
disp(%i)
disp("value of boolean True:")
disp(%t)
disp("Value of boolean False:")
disp(%f)
disp("value of Not−a−number variable i.e. nan:")
disp(%nan)
